odyssey_dependencies:
  - build-essential
  - cmake 
  - "postgresql-server-dev-{{ postgresql_version }}"
  - gcc
  - openssl
  - git
  - libpam0g-dev
  - clang
  - gdb
  - valgrind
  - libpq5
  - libpq-dev
  - vim
  - postgresql-common


odyssey_pool_mode: session
odyssey_client_max: 10000
odyssey_pool_size: 600
odyssey_listen_port: 6433
odyssey_workers: 4
