postgresql_hba_list:
 - contype: host
   users: all
   source: 10.0.0.0/8
   databases: all
   method: scram-sha-256
 - contype: host
   users: all
   source: 127.0.0.1/32
   databases: all
   method: scram-sha-256

postgresql_cybertec_config: false
