pvm_list:
  - name: pg14
    memory: 16384
    cores: 8
    disks:
      - name: scsi0
        size: 100
        cache: unsafe
        iothread: true
        ssd : true
  - name: pg15
    memory: 16384
    cores: 8
    disks:
      - name: scsi0
        size: 100
        cache: unsafe
        iothread: true
        ssd : true
