---
swap_file_path: /swapfile
#swap_file_size_mb: '512'
swap_file_size_mb: "{{ [(ansible_memory_mb.real.total / 2), 65536] | min | int }}"
swap_file_state: present
swap_file_create_command: "dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_file_size_mb }}"

swap_test_mode: false
