---
dependencies: []

galaxy_info:
  role_name: swap
  author: community
  description: swap file create
  company: "Midwestern Mac, LLC"
  license: "MIT"
  min_ansible_version: 2.4
  platforms:

    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - swap

