- hosts: all
  gather_facts: true
  become: true
  tasks:

    - name: UPDATE ALL PACKAGES
      ansible.builtin.package:
        name: "*"
        state: latest
        update_cache: true
      notify:
        - REBOOT

    - name: Install base packages
      ansible.builtin.package:
        name:
          - mc
          - htop
          - iotop
          - net-tools
          - atop
          - htop
          - unzip
          - netperf
          - python3-pip
          - sysstat
          - sysfsutils
          - wget
          - acl

    - name: PGCENTER INSTALLATION
      ansible.builtin.shell: "curl -sLO https://github.com/lesovsky/pgcenter/releases/download/v0.9.2/pgcenter_0.9.2_linux_amd64.deb && dpkg -i pgcenter_0.9.2_linux_amd64.deb"

  handlers:
    - name: REBOOT
      ansible.builtin.reboot: