- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: IMPORT POSTGRESQL REPO KEY
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: ADD POSTGRESQL REPO
      ansible.builtin.apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        state: present

    - name: INSTALL POSTGRESQL PACKAGES
      ansible.builtin.package:
        name:
          - "postgresql-{{ postgresql_version }}"
          - pgtop
          - python3-psycopg2
          - pgbouncer
        update_cache: true

    - name: CHECK BACKUP CONFIG EXISTS
      ansible.builtin.stat:
        path: "/root/postgresql.conf"
      register: _backup_config

    - name: BACKUP CONFIG IF NOT EXISTS
      ansible.builtin.copy:
        remote_src: true
        src: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
        dest: "/root/postgresql.conf"
      when: not _backup_config.stat.exists
  
