- hosts: all
  gather_facts: true
  become: true
  become_user: postgres

  tasks:

    - name: VACUUM FULL ANALYZE ALL DBS
      shell: |
        vacuumdb -a -f -z -v
      args:
        chdir: /var/lib/postgresql/
      when: pgbench_vacuumfull|bool
      tags:
        - pgbench_vacuumfull

    - name: RUN PGBENCH INTERNAL SIMPLE
      vars:
        workload_db_name: postgres
        pgbench_protocol: simple
      shell: |
        /usr/lib/postgresql/{{ postgresql_version }}/bin/pgbench \
        -c {{ pgbench_clients }} \
        -j {{ pgbench_jobs }} \
        -T {{ pgbench_time }} \
        -b {{ pgbench_builtin_workload }} \
        -U postgres {{ workload_db_name }} \
        -M {{ pgbench_protocol }} \
        -v 

      args:
        chdir: /var/lib/postgresql/
      register: _pgbench_internal_simple
      tags: 
        - simple
      

    - name: SHOW PGBENCH INTERNAL SIMPLE RESULTS
      debug:
        var: _pgbench_internal_simple.stdout
      tags: 
        - simple

    - name: RUN PGBENCH INTERNAL EXTENDED
      vars:
        workload_db_name: postgres
        pgbench_protocol: extended
      shell: |
        /usr/lib/postgresql/{{ postgresql_version }}/bin/pgbench \
        -c {{ pgbench_clients }} \
        -j {{ pgbench_jobs }} \
        -T {{ pgbench_time }} \
        -b {{ pgbench_builtin_workload }} \
        -U postgres {{ workload_db_name }} \
        -M {{ pgbench_protocol }} \
        -v 

      args:
        chdir: /var/lib/postgresql/
      register: _pgbench_internal_extended
      tags: 
        - extended      

    - name: SHOW PGBENCH INTERNAL EXTENDED RESULTS
      debug:
        var: _pgbench_internal_extended.stdout
      tags: 
        - extended  

    - name: RUN PGBENCH EXTERNAL
      shell: |
        /usr/lib/postgresql/{{ postgresql_version }}/bin/pgbench \
        -c {{ pgbench_clients }} \
        -j {{ pgbench_jobs }} \
        -T {{ pgbench_time }} \
        -f {{ pgbench_workload_file }} \
        -U postgres {{ workload_db_name }}
      args:
        chdir: /var/lib/postgresql/
      register: _pgbench_external
      tags: 
        - external        

    - name: SHOW PGBENCH EXTERNAL RESULTS
      debug:
        var: _pgbench_external.stdout
      tags: 
        - external   